// flow-typed signature: 5c74fa9d4bae9a10f821f8dc71fe2d03
// flow-typed version: <<STUB>>/camelcase-keys-recursive_v^0.8.2/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'camelcase-keys-recursive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'camelcase-keys-recursive' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'camelcase-keys-recursive/lib/index' {
  declare module.exports: any
}

// Filename aliases
declare module 'camelcase-keys-recursive/lib/index.js' {
  declare module.exports: $Exports<'camelcase-keys-recursive/lib/index'>
}
