// flow-typed signature: 34db492373691ab8de1a0860a1821230
// flow-typed version: <<STUB>>/s2s-plugins-redux_v^0.1.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   's2s-plugins-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 's2s-plugins-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 's2s-plugins-redux/index' {
  declare module.exports: $Exports<'s2s-plugins-redux'>;
}
declare module 's2s-plugins-redux/index.js' {
  declare module.exports: $Exports<'s2s-plugins-redux'>;
}
