// flow-typed signature: 10dccb7f23015b09feb48f45d0cbdd94
// flow-typed version: <<STUB>>/s2s_v^0.7.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   's2s'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 's2s' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 's2s/bin/s2s' {
  declare module.exports: any;
}

declare module 's2s/dest/cli/index' {
  declare module.exports: any;
}

declare module 's2s/dest/cli/loadConfig' {
  declare module.exports: any;
}

declare module 's2s/dest/handlers/plugins' {
  declare module.exports: any;
}

declare module 's2s/dest/handlers/templates' {
  declare module.exports: any;
}

declare module 's2s/dest/hooks/index' {
  declare module.exports: any;
}

declare module 's2s/dest/hooks/prettier' {
  declare module.exports: any;
}

declare module 's2s/dest/hooks/run' {
  declare module.exports: any;
}

declare module 's2s/dest/index' {
  declare module.exports: any;
}

declare module 's2s/dest/reporters/index' {
  declare module.exports: any;
}

declare module 's2s/dest/types' {
  declare module.exports: any;
}

declare module 's2s/dest/utils/index' {
  declare module.exports: any;
}

declare module 's2s/dest/utils/lock' {
  declare module.exports: any;
}

// Filename aliases
declare module 's2s/bin/s2s.js' {
  declare module.exports: $Exports<'s2s/bin/s2s'>;
}
declare module 's2s/dest/cli/index.js' {
  declare module.exports: $Exports<'s2s/dest/cli/index'>;
}
declare module 's2s/dest/cli/loadConfig.js' {
  declare module.exports: $Exports<'s2s/dest/cli/loadConfig'>;
}
declare module 's2s/dest/handlers/plugins.js' {
  declare module.exports: $Exports<'s2s/dest/handlers/plugins'>;
}
declare module 's2s/dest/handlers/templates.js' {
  declare module.exports: $Exports<'s2s/dest/handlers/templates'>;
}
declare module 's2s/dest/hooks/index.js' {
  declare module.exports: $Exports<'s2s/dest/hooks/index'>;
}
declare module 's2s/dest/hooks/prettier.js' {
  declare module.exports: $Exports<'s2s/dest/hooks/prettier'>;
}
declare module 's2s/dest/hooks/run.js' {
  declare module.exports: $Exports<'s2s/dest/hooks/run'>;
}
declare module 's2s/dest/index.js' {
  declare module.exports: $Exports<'s2s/dest/index'>;
}
declare module 's2s/dest/reporters/index.js' {
  declare module.exports: $Exports<'s2s/dest/reporters/index'>;
}
declare module 's2s/dest/types.js' {
  declare module.exports: $Exports<'s2s/dest/types'>;
}
declare module 's2s/dest/utils/index.js' {
  declare module.exports: $Exports<'s2s/dest/utils/index'>;
}
declare module 's2s/dest/utils/lock.js' {
  declare module.exports: $Exports<'s2s/dest/utils/lock'>;
}
