// flow-typed signature: 8e7fd22f906687c47d8b3f5a9efd5a14
// flow-typed version: <<STUB>>/@material-ui/lab_v^1.0.0-alpha.5/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/lab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/lab' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/lab/index.es' {
  declare module.exports: any
}

declare module '@material-ui/lab/Slider/index' {
  declare module.exports: any
}

declare module '@material-ui/lab/Slider/Slider' {
  declare module.exports: any
}

declare module '@material-ui/lab/SpeedDial/index' {
  declare module.exports: any
}

declare module '@material-ui/lab/SpeedDial/SpeedDial' {
  declare module.exports: any
}

declare module '@material-ui/lab/SpeedDialAction/index' {
  declare module.exports: any
}

declare module '@material-ui/lab/SpeedDialAction/SpeedDialAction' {
  declare module.exports: any
}

declare module '@material-ui/lab/SpeedDialIcon/index' {
  declare module.exports: any
}

declare module '@material-ui/lab/SpeedDialIcon/SpeedDialIcon' {
  declare module.exports: any
}

declare module '@material-ui/lab/utils/clamp' {
  declare module.exports: any
}

// Filename aliases
declare module '@material-ui/lab/index.es.js' {
  declare module.exports: $Exports<'@material-ui/lab/index.es'>
}
declare module '@material-ui/lab/index' {
  declare module.exports: $Exports<'@material-ui/lab'>
}
declare module '@material-ui/lab/index.js' {
  declare module.exports: $Exports<'@material-ui/lab'>
}
declare module '@material-ui/lab/Slider/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/Slider/index'>
}
declare module '@material-ui/lab/Slider/Slider.js' {
  declare module.exports: $Exports<'@material-ui/lab/Slider/Slider'>
}
declare module '@material-ui/lab/SpeedDial/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDial/index'>
}
declare module '@material-ui/lab/SpeedDial/SpeedDial.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDial/SpeedDial'>
}
declare module '@material-ui/lab/SpeedDialAction/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialAction/index'>
}
declare module '@material-ui/lab/SpeedDialAction/SpeedDialAction.js' {
  declare module.exports: $Exports<
    '@material-ui/lab/SpeedDialAction/SpeedDialAction',
  >
}
declare module '@material-ui/lab/SpeedDialIcon/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialIcon/index'>
}
declare module '@material-ui/lab/SpeedDialIcon/SpeedDialIcon.js' {
  declare module.exports: $Exports<
    '@material-ui/lab/SpeedDialIcon/SpeedDialIcon',
  >
}
declare module '@material-ui/lab/utils/clamp.js' {
  declare module.exports: $Exports<'@material-ui/lab/utils/clamp'>
}
